title: Hyde
email: konstantin.dankov@gmail.com
description: This is scary, but awesome!
destination: docs
baseurl: ""
# baseurl: "/su-fe2-hyde"
url: ""
twitter_username: kdankov
github_username: kdankov

exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md]
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
